### ISSUE TITLE
[Bug] Color highlight breaks when using `@import 'foo';`

### ISSUE THREAD

**Issue by wenfangdu** [enyancc/vscode-ext-color-highlight#146]
Test Cases:

test.scss

```scss
@import 'foo';

body {
  //          👇 not highlighted
  background: #000;
}
```

```scss
@import '';

body {
  //          👇 highlighted
  background: #000;
}
```

```scss
body {
  //          👇 highlighted
  background: #000;
}
```
